stages:
    - lint
    - build
    - release
    - deploy

variables:
    CONTAINER_RELEASE_IMAGE_BASE: $CI_REGISTRY/images/k-search-engine
    GIT_SUBMODULE_STRATEGY: normal

test-shell-syntax:
  stage: lint
  image: "docker.klink.asia/alessio.vertemati/shellcheck-ci:latest"
  script:
    - shellcheck ./docker/start.sh
  tags:
    - docker

build:
    stage: build
    tags:
        - dind
    script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker build -t $CI_REGISTRY_IMAGE:${CI_COMMIT_REF_NAME//\//-} .
        - docker tag $CI_REGISTRY_IMAGE:${CI_COMMIT_REF_NAME//\//-} "k-search-engine"
        - docker-compose -f ./docker-compose.test.yml up -d
        - sleep 5 # wait for 5 seconds, this should be enough to see startup log entries
        - docker-compose -f ./docker-compose.test.yml logs > ./docker_ouput.log 2>&1
        - docker-compose -f ./docker-compose.test.yml down
        - grep -c "Welcome to Apache Solr" ./docker_ouput.log > null || echo "Welcome phrase not found" && return 1
        - grep -c "/opt/solr/k-search" ./docker_ouput.log > null || echo "Solr home not found" && return 1
        - docker push $CI_REGISTRY_IMAGE:${CI_COMMIT_REF_NAME//\//-}

push_master:
    stage: release
    tags:
        - shell
    script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker pull $CI_REGISTRY_IMAGE:${CI_COMMIT_REF_NAME//\//-}
        - docker login -u $REGISTRY_RELEASE_USERNAME -p $REGISTRY_RELEASE_PASSWORD $CI_REGISTRY
        - docker tag $CI_REGISTRY_IMAGE:${CI_COMMIT_REF_NAME//\//-} "$CONTAINER_RELEASE_IMAGE_BASE:latest"
        - docker push "$CONTAINER_RELEASE_IMAGE_BASE:latest"
    only:
        - master

push_tags:
    stage: release
    tags:
        - shell
    script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker pull $CI_REGISTRY_IMAGE:${CI_COMMIT_REF_NAME//\//-}
        - docker login -u $REGISTRY_RELEASE_USERNAME -p $REGISTRY_RELEASE_PASSWORD $CI_REGISTRY
        - docker tag $CI_REGISTRY_IMAGE:${CI_COMMIT_REF_NAME//\//-} "$CONTAINER_RELEASE_IMAGE_BASE:${CI_COMMIT_REF_NAME/v/}"
        - docker push "$CONTAINER_RELEASE_IMAGE_BASE:${CI_COMMIT_REF_NAME/v/}"
    only:
        - tags

deploy_integration:
  environment: Integration
  when: manual
  stage: deploy
  tags:
    - shell
    - deploy
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:${CI_COMMIT_REF_NAME/v/}
    - cd ${INTEGRATION_DOCKER_FOLDER}
    - docker tag $CI_REGISTRY_IMAGE:${CI_COMMIT_REF_NAME/v/} $INTEGRATION_DOCKER_IMAGE
    - docker-compose down && docker-compose up -d

deploy_review:
  environment: Review
  when: manual
  stage: deploy
  tags:
    - shell
    - deploy
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:${CI_COMMIT_REF_NAME/v/}
    - cd ${REVISION_DOCKER_FOLDER}
    - docker tag $CI_REGISTRY_IMAGE:${CI_COMMIT_REF_NAME/v/} $REVISION_DOCKER_IMAGE
    - docker-compose down && docker-compose up -d

