sudo: required

services:
  - docker

language: java

before_script:
  # - shellcheck ./start.sh
  - docker build -t k-search-engine .

script:
  - docker-compose -f ./docker-compose.test.yml up -d
  - sleep 5 # wait for 5 seconds, this should be enough to see startup log entries
  - docker-compose -f ./docker-compose.test.yml logs > ./docker_ouput.log 2>&1
  - grep -c "Welcome to Apache Solr" ./docker_ouput.log > null || echo "Welcome phrase not found" && return 1
  - grep -c "/opt/solr/k-search" ./docker_ouput.log > null || echo "Solr home not found" && return 1

after_script:
  - docker-compose -f ./docker-compose.test.yml down