sudo: required

services:
  - docker

language: java

branches:
  only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
  - /^\d+\.\d+?$/

notifications:
  email:
    on_success: never

before_script:
  - shellcheck ./start.sh
  - docker build -t k-search-engine .

script:
  - docker-compose -f ./docker-compose.test.yml up -d
  - sleep 5 # wait for 5 seconds, this should be enough to see startup log entries
  - docker-compose -f ./docker-compose.test.yml logs &>docker_output.log
  - grep -c "Welcome to Apache Solr" docker_output.log > /dev/null
  - grep -c "/opt/solr/k-search" docker_output.log > /dev/null

after_script:
  - docker-compose -f ./docker-compose.test.yml down
