## Docker compose file for testing the generated docker image
## This docker compose can be used also to start the necessary services for integration tests

version: "2"

networks:
  internal:

services:
  engine:
    build: "."
    image: "k-search-engine"
    environment:
      INDEX_NAME: testing
    volumes:
      - "/opt/solr/k-search/k-search/data"
    expose:
      - "8983"
    networks:
      - internal
